name: acdg_system
description: ACDG System - Frontend integrado da ACDG Technology.
publish_to: 'none'
version: 0.1.2

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  auth:
    path: ../../packages/auth
  network:
    path: ../../packages/network
  persistence:
    path: ../../packages/persistence
  social_care:
    path: ../../packages/social_care
  design_system:
    path: ../../packages/design_system
  shared:
    path: ../../bff/shared
  social_care_desktop:
    path: ../../bff/social_care_desktop
  go_router: ^17.1.0
  provider: ^6.1.5
  dio: ^5.9.2
  google_fonts: ^8.0.2
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  sentry_flutter: ^9.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.13.1
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  msix: ^3.16.13

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/satoshi/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-Bold.ttf
          weight: 700

    - family: Erode
      fonts:
        - asset: assets/fonts/erode/Erode-Light.ttf
          weight: 300
        - asset: assets/fonts/erode/Erode-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/erode/Erode-Regular.ttf
          weight: 400
        - asset: assets/fonts/erode/Erode-Medium.ttf
          weight: 500
        - asset: assets/fonts/erode/Erode-MediumItalic.ttf
          weight: 500
          style: italic

msix_config:
  display_name: "ACDG System"
  publisher_display_name: "ACDG Technology"
  identity_name: "com.acdgbrasil.acdgSystem"
  msix_version: "0.1.0.0"
  capabilities: "internetClient, location"
  install_certificate: false
