/// Localization constants for the Family Composition feature.
abstract final class FamilyCompositionLn10 {
  // ── Page ──────────────────────────────────────────────────────

  static const String pageTitle = 'Composição Familiar';
  static const String navFamilies = 'Famílias';
  static const String navRegistration = 'Cadastro';
  static const String addMemberLabel = 'Adicionar membro';
  static const String btnCancel = 'Cancelar';
  static const String btnSave = 'Salvar Cadastro';
  static const String btnObservations = 'Observações';

  // ── Table ─────────────────────────────────────────────────────

  static const String colName = 'Nome';
  static const String colAge = 'Idade';
  static const String colSex = 'Sexo';
  static const String colRelationship = 'Parentesco';
  static const String colResides = 'Reside';
  static const String colPcd = 'PcD';
  static const String colDocuments = 'Documentos Necessários';
  static const String ageYears = 'anos';
  static const String badgeReference = 'Referência';
  static const String badgeCaregiver = 'Cuidador';
  static const String refRelationship = '01 - Pessoa de Referência';
  static const String tooltipEdit = 'Editar';
  static const String tooltipRemove = 'Remover';
  static const String tooltipSetCaregiver = 'Definir como cuidador';
  static const String tooltipRemoveCaregiver = 'Remover cuidador';
  static const String sexMale = 'Masculino';
  static const String sexFemale = 'Feminino';
  static const String sexOther = 'Outro';
  static const String residesYes = 'Sim';
  static const String residesNo = 'Não';
  static const String docsNone = 'Nenhum';

  // ── Empty state ───────────────────────────────────────────────

  static const String emptyTitle = 'Nenhum outro membro adicionado.';
  static const String emptySubtitle =
      'Clique em + para adicionar o primeiro membro da família.';

  // ── Modal — Add/Edit member ───────────────────────────────────

  static const String modalAddTitle = 'Adicionar Membro';
  static const String modalEditTitle = 'Editar Membro';
  static const String modalSave = 'Salvar';
  static const String modalNote =
      'Ao salvar: POST /family-members. Se cuidador marcado, dispara também PUT /primary-caregiver.';
  static const String fieldName = 'Nome Completo';
  static const String fieldNamePlaceholder = 'Nome completo do membro';
  static const String fieldBirthDate = 'Data de Nascimento';
  static const String fieldBirthDatePlaceholder = 'DD / MM / AAAA';
  static const String fieldSex = 'Sexo';
  static const String fieldResiding = 'Reside com o paciente?';
  static const String fieldPcd = 'Pessoa com deficiência';
  static const String fieldCaregiver = 'Cuidador principal?';
  static const String fieldDocuments = 'Documentos Necessários';
  static const String fieldRelationship = 'Parentesco';
  static const String fieldRelationshipPlaceholder = 'Selecione';
  static const String autoGeneratedTitle = 'Gerado automaticamente';

  // ── Confirm — Remove member ───────────────────────────────────

  static const String removeTitle = 'Remover membro da família?';
  static const String removeMessage = 'Você está prestes a remover';
  static const String removeMessageSuffix = 'da composição familiar.';
  static const String removeCaregiverWarning =
      'é o cuidador principal. Ao remover, a família ficará sem cuidador designado. Você pode designar outro membro depois.';
  static const String removeIrreversible =
      'Esta ação não pode ser desfeita.';
  static const String btnRemoveConfirm = 'Sim, remover';

  // ── Confirm — Caregiver change ────────────────────────────────

  static const String caregiverTitle = 'Trocar cuidador principal?';
  static const String caregiverCurrentIs = 'é o cuidador atual.';
  static const String caregiverWillBecome =
      'se tornará o novo cuidador principal';
  static const String caregiverLoseStatus = 'e perderá esse status.';
  static const String caregiverApiNote =
      'Isso vai disparar PUT /patients/{id}/primary-caregiver com o novo memberPersonId.';
  static const String btnCaregiverConfirm = 'Confirmar troca';

  // ── Age Profile ───────────────────────────────────────────────

  static const String ageProfileTitle = 'Perfil Etário Familiar';
  static const String ageProfileAuto =
      'Calculado automaticamente. Atualiza ao adicionar ou remover membros.';
  static const String ageColRange = 'Faixa Etária';
  static const String ageColCount = 'Qtd.';
  static const String age0to6 = '0 a 6 anos';
  static const String age7to14 = '7 a 14 anos';
  static const String age15to17 = '15 a 17 anos';
  static const String age18to29 = '18 a 29 anos';
  static const String age30to59 = '30 a 59 anos';
  static const String age60to64 = '60 a 64 anos';
  static const String age65to69 = '65 a 69 anos';
  static const String age70plus = '70 anos ou mais';

  // ── Specificities (readonly section) ──────────────────────────

  static const String specificitiesTitle = 'Especificidades';
  static const String specCigana = 'Família cigana';
  static const String specQuilombola = 'Família quilombola';
  static const String specRibeirinha = 'Família ribeirinha';
  static const String specHomeless = 'Família / pessoa em situação de rua';

  // ── Validation ────────────────────────────────────────────────

  static const String errorRequired = 'Campo obrigatório';
  static const String errorMinChars3 = 'Mínimo de 3 caracteres';
  static const String errorDateIncomplete = 'Data incompleta';
  static const String errorDateInvalid = 'Data inválida';
  static const String errorSelectSex = 'Selecione o sexo';
  static const String errorSelectRelationship = 'Selecione o parentesco';
  static const String errorSelectResiding = 'Campo obrigatório';
  static const String errorSelectPcd = 'Campo obrigatório';
  static const String errorBirthDate = 'Informe a data de nascimento';
}
