name: core
description: Core package - network, auth, platform, base classes.
version: 0.1.0
publish_to: 'none'

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  oidc: ^0.14.0+2
  oidc_default_store: ^0.6.0+2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
