import 'package:core_contracts/core_contracts.dart';
import 'package:shared/shared.dart';
import 'package:test/test.dart';

import 'package:social_care_web/src/intents/update_housing_condition_intent.dart';
import 'package:social_care_web/src/intents/uuid_validation.dart';

import '../_test_uuids.dart';

/// Wave 0 RED contract for [UpdateHousingConditionIntent].
///
/// Canon (A10 refinement of A07/A08/A09):
/// - Parse strategy: try/catch over `fromJson` generated by json_serializable
///   (NOT a P2 if-case on 15+ fields — see REPORT).
/// - Structural error message: `'Invalid update-housing body: missing or
///   malformed required fields'`. The message NEVER enumerates the offending
///   fields nor echoes user-supplied values (shape-leak protection).
/// - Private `_UpdateHousingConditionParseError with Equatable implements
///   Exception`.

Map<String, dynamic> _validBody() => {
  'type': 'OWNED',
  'wallMaterial': 'BRICK',
  'numberOfRooms': 3,
  'numberOfBedrooms': 2,
  'numberOfBathrooms': 1,
  'waterSupply': 'PUBLIC_NETWORK',
  'hasPipedWater': true,
  'electricityAccess': 'REGULAR',
  'sewageDisposal': 'PUBLIC_NETWORK',
  'wasteCollection': 'COLLECTED',
  'accessibilityLevel': 'FULLY_ACCESSIBLE',
  'isInGeographicRiskArea': false,
  'hasDifficultAccess': false,
  'isInSocialConflictArea': false,
  'hasDiagnosticObservations': false,
};

void main() {
  group('UpdateHousingConditionIntent', () {
    test('constructs with patientId + request', () {
      const request = UpdateHousingConditionRequest(
        type: 'OWNED',
        wallMaterial: 'BRICK',
        numberOfRooms: 3,
        numberOfBedrooms: 2,
        numberOfBathrooms: 1,
        waterSupply: 'PUBLIC_NETWORK',
        hasPipedWater: true,
        electricityAccess: 'REGULAR',
        sewageDisposal: 'PUBLIC_NETWORK',
        wasteCollection: 'COLLECTED',
        accessibilityLevel: 'FULLY_ACCESSIBLE',
        isInGeographicRiskArea: false,
        hasDifficultAccess: false,
        isInSocialConflictArea: false,
        hasDiagnosticObservations: false,
      );

      const intent = UpdateHousingConditionIntent(
        patientId: kPatientUuid,
        request: request,
      );

      expect(intent.patientId, equals(kPatientUuid));
      expect(intent.request, equals(request));
    });

    test('instances with equal payload are equal (Equatable)', () {
      const request = UpdateHousingConditionRequest(
        type: 'OWNED',
        wallMaterial: 'BRICK',
        numberOfRooms: 3,
        numberOfBedrooms: 2,
        numberOfBathrooms: 1,
        waterSupply: 'PUBLIC_NETWORK',
        hasPipedWater: true,
        electricityAccess: 'REGULAR',
        sewageDisposal: 'PUBLIC_NETWORK',
        wasteCollection: 'COLLECTED',
        accessibilityLevel: 'FULLY_ACCESSIBLE',
        isInGeographicRiskArea: false,
        hasDifficultAccess: false,
        isInSocialConflictArea: false,
        hasDiagnosticObservations: false,
      );

      const a = UpdateHousingConditionIntent(
        patientId: kPatientUuid,
        request: request,
      );
      const b = UpdateHousingConditionIntent(
        patientId: kPatientUuid,
        request: request,
      );

      expect(a, equals(b));
      expect(a.hashCode, equals(b.hashCode));
    });

    test('instances with different patientId are not equal', () {
      const request = UpdateHousingConditionRequest(
        type: 'OWNED',
        wallMaterial: 'BRICK',
        numberOfRooms: 3,
        numberOfBedrooms: 2,
        numberOfBathrooms: 1,
        waterSupply: 'PUBLIC_NETWORK',
        hasPipedWater: true,
        electricityAccess: 'REGULAR',
        sewageDisposal: 'PUBLIC_NETWORK',
        wasteCollection: 'COLLECTED',
        accessibilityLevel: 'FULLY_ACCESSIBLE',
        isInGeographicRiskArea: false,
        hasDifficultAccess: false,
        isInSocialConflictArea: false,
        hasDiagnosticObservations: false,
      );

      const a = UpdateHousingConditionIntent(
        patientId: kPatientUuid,
        request: request,
      );
      const b = UpdateHousingConditionIntent(
        patientId: kPatientUuidAlt,
        request: request,
      );

      expect(a, isNot(equals(b)));
    });

    group('parseFromBody — Result<UpdateHousingConditionIntent>', () {
      test('returns Success when body is valid', () {
        final result = UpdateHousingConditionIntent.parseFromBody(
          kPatientUuid,
          _validBody(),
        );

        expect(result, isA<Success<UpdateHousingConditionIntent>>());
      });

      test('Success payload preserves patientId and request fields', () {
        final result = UpdateHousingConditionIntent.parseFromBody(
          kPatientUuid,
          _validBody(),
        );

        switch (result) {
          case Success(:final value):
            expect(value.patientId, equals(kPatientUuid));
            expect(value.request.type, equals('OWNED'));
            expect(value.request.numberOfRooms, equals(3));
            expect(value.request.hasPipedWater, isTrue);
          case Failure():
            fail('Expected Success, got Failure');
        }
      });

      test('returns Failure when required field type is missing', () {
        final body = _validBody()..remove('type');

        final result = UpdateHousingConditionIntent.parseFromBody(
          kPatientUuid,
          body,
        );

        expect(result, isA<Failure<UpdateHousingConditionIntent>>());
      });

      test('returns Failure when body is empty', () {
        final result = UpdateHousingConditionIntent.parseFromBody(
          kPatientUuid,
          const {},
        );

        expect(result, isA<Failure<UpdateHousingConditionIntent>>());
      });

      test('Failure message is structural (no field values echoed)', () {
        // Include a marker value that MUST NOT surface in the error.
        final body = _validBody()..['type'] = 'SECRET_MARKER_ZZZ';
        body.remove('numberOfRooms'); // force failure via missing int

        final result = UpdateHousingConditionIntent.parseFromBody(
          kPatientUuid,
          body,
        );

        switch (result) {
          case Success():
            fail('Expected Failure');
          case Failure(:final error):
            final text = error.toString();
            expect(
              text,
              equals(
                'Invalid update-housing body: '
                'missing or malformed required fields',
              ),
            );
            expect(text, isNot(contains('SECRET_MARKER_ZZZ')));
            expect(text, isNot(contains('numberOfRooms')));
        }
      });

      test(
        'returns Failure with UuidPathParamError when path id is not UUID v4',
        () {
          final result = UpdateHousingConditionIntent.parseFromBody(
            kNonUuid,
            _validBody(),
          );

          switch (result) {
            case Success():
              fail('Expected Failure for non-UUID path id');
            case Failure(:final error):
              expect(error, isA<UuidPathParamError>());
              expect(
                (error as UuidPathParamError).fieldName,
                equals('patientId'),
              );
              // PII safety: error must not echo the raw path input.
              expect(error.toString(), isNot(contains(kNonUuid)));
          }
        },
      );
    });
  });
}
